host: ldap-sandbox.in.didww.com
port: 636
# attribute: uid # default
base: ou=employees,dc=didww,dc=com
encryption: simple_tls
group_base: ou=groups,dc=didww,dc=com # optional
#group_attribute: uniqueMember # default
required_groups:
  - attribute: "uniqueMember"
    base: "cn=apiConsole,ou=groups,dc=didww,dc=com"
